### ISSUE TITLE
Plugin doesn't work when variable and type are named exactly the same.

### ISSUE THREAD

**Issue by ghost** [Gerrit0/typedoc-plugin-zod#2]
Hello,

This code snippet gives the expected output:
```ts
import { number, object, string, TypeOf, unknown } from "zod";

export const foo = object({
  a: string(),
  b: number(),
  c: unknown()
});

// I didn't know TypeOf would work but they are apparently the same. (I prefer TypeOf over infer because I use the named imports).
export type Foo = TypeOf<typeof foo>;
```

![image](https://github.com/Gerrit0/typedoc-plugin-zod/assets/139470244/9f213f87-5f89-4e0a-a4ae-204e0817818c)

However, when naming the variable and type exactly the same, like so:
```ts
import { number, object, string, TypeOf, unknown } from "zod";

export const Foo = object({
  a: string(),
  b: number(),
  c: unknown()
});

export type Foo = TypeOf<typeof Foo>;
```
![image](https://github.com/Gerrit0/typedoc-plugin-zod/assets/139470244/1a783e6e-858c-4ae7-bb7f-097e3c9a7ca1)

The output is different.

**Comment by Gerrit0** [comment]
Yikes, that's some ugly output... TypeDoc also has some issues with reflections which share the same name, hopefully this can be fixed without needing to fix those...
