### ISSUE TITLE
Any idea how to get enums working?

### ISSUE THREAD

**Issue by lightswitch05** [Gerrit0/typedoc-plugin-zod#4]
Hello and thank you for providing this library! I'm wondering how I can get enums working? I would like to use real TypeScript enums like:

```
enum Color {
    BLUE = 'Blue',
    RED = 'Red,
}
```

and then use it:

```
const vehicle = z.object({
    color: z.nativeEnum(Color)
})
```

When I generate the docs, I can get something like this:

```
Vehicle: {
    color: Color;
}
```

The `Color` in the documentation is named the same as the `Color` enum - but there are no links or indication that its the same type. I could add a `see {@link Color}` to make a link within the doc notes - but its not quite the same thing. Any ideas?

**Comment by Gerrit0** [comment]
Huh, that's a strange one. This plugin basically just grabs the resolved type and passes it off to TypeDoc for resolution... TypeDoc sees that it is a reference, but the type apparently doesn't have a symbol at that point, so doesn't get linked to the enum. 

This is something that needs to be fixed on TypeDoc's side, I've opened https://github.com/TypeStrong/typedoc/issues/2508 to track that.

**Comment by lightswitch05** [comment]
I'm glad it's not just me doing something wrong 😆. Thank you for the confirmation and opening the related issue!

**Comment by Gerrit0** [comment]
This should work with TypeDoc 0.25.10

**Comment by lightswitch05** [comment]
I just tried it out and it works great, thank you!
