### ISSUE TITLE
Broken link to the example in your README.md

### ISSUE THREAD

**Issue by igloo1505** [Gerrit0/typedoc-plugin-zod#5]
Like the title says, the link in your Readme to the example is broken, and kinda crucial.

**Comment by Gerrit0** [comment]
... I don't understand GitHub pages, it apparently decided that because my gerrit0.github.io repo uses a custom domain, everything else should too...

**Comment by Gerrit0** [comment]
Apparently that isn't the issue, it's that the pages build has been broken for a while, thanks for the report!

Fixed with 33ba4570dee43b0f47aa4260a18ae4eaa73ff558
