### ISSUE TITLE
Include JSDoc comments on Zod schemas in type definitions

### ISSUE THREAD

**Issue by coreyward** [Gerrit0/typedoc-plugin-zod#7]
I pretty regularly define Zod schemas with inline JSDoc comments. VSCode/IntelliSense picks these up and includes them when showing types on hover, even for the inferred types:

<img width="356" alt="Screenshot 2024-08-18 at 11 36 30 AM" src="https://github.com/user-attachments/assets/2e93f425-d842-4751-ac29-5fa1999eacd7">
<img width="352" alt="Screenshot 2024-08-18 at 11 36 22 AM" src="https://github.com/user-attachments/assets/f9c8b006-f7ec-4d94-9f5f-cdbe3019e295">
<img width="395" alt="Screenshot 2024-08-18 at 11 36 11 AM" src="https://github.com/user-attachments/assets/b5eff9cc-58c3-4a05-b523-837b1d48c08b">

TypeDoc with this plugin, however, only shows the comment for the object schema type on the Zod schema variable, not on the type definition:

<img width="594" alt="Screenshot 2024-08-18 at 11 38 31 AM" src="https://github.com/user-attachments/assets/e069cda8-3277-4f92-b0d3-a679074ce46a">
<img width="584" alt="Screenshot 2024-08-18 at 11 38 46 AM" src="https://github.com/user-attachments/assets/75f8c97a-0275-49bc-84b2-aa570ead4205">

It would be great to have the JSDoc entry copied over into the type definition as well, so that the "Some example documentation" line shows on the Type Alias page shown in the first TypeDoc screenshot. 

Is this possible?

**Comment by Gerrit0** [comment]
Yes, possible and pretty easy too!

**Comment by coreyward** [comment]
Wow, that was fast! Thank you!
